name: Run tests

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Скачивание selenoid"
        run: curl -s https://aerokube.com/cm/bash | bash
      - name: "Расширение прав на запуск Selenoid"
        run: chmod +x ./cm
      - name: "Запуск selenoid"
        run: ./cm selenoid start --vnc
      - name: "Запуск selenoid-ui"
        run: ./cm selenoid-ui start
      - name: "Использование main репозитория"
        uses: actions/checkout@v3
      - name: "Запуск тестов"
        run: mvn clean test
        continue-on-error: true
      - name: "Генерация аллюр"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки "
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history
